name: Docker Build and Push Backend

on:
  push:
    paths:
      - '**'
      - '!serverless/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - '**'
      - '!serverless/**'
    branches: [ "main" ]



env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GCP_REGION: us-west2
  GCP_PROJECT_ID: bike-fitting-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Retag and push to Google Cloud Artifact Registry
        run: |
          # Get the first tag from the metadata step
          SOURCE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d' ' -f1)
          
          # Create the destination tag for GCP Artifact Registry
          DEST_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/bike-fitting-api/camber-bikes:latest"
          
          # Retag the image
          docker tag $SOURCE_TAG $DEST_TAG
          
          # Push to GCP Artifact Registry
          docker push $DEST_TAG