name: Docker Build and Push Backend to GCP Artefact Registry

on:
  push:
    paths:
      - '**'
      - '!serverless/**'
    branches: [ "main" ]
  workflow_dispatch:

env:
  GCP_REGION: us-west2
  GCP_PROJECT_ID: bike-fitting-api
  GCP_IMAGE_TAG: us-west2-docker.pkg.dev/bike-fitting-api/camber-bikes/backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev
      - name: Build and push Docker image to Artefact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{env.GCP_IMAGE_TAG}}

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME="${{ secrets.CLOUD_RUN_SERVICE }}"
          REGION="${{ secrets.CLOUD_RUN_REGION }}"
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.CLOUD_RUN_IMAGE }}:latest"
          
          gcloud run deploy ${{secrets.CLOUD_RUN_SERVICE}} \
            --image ${{env.GCP_IMAGE_TAG}}:latest \
            --region ${{env.GCP_REGION}} \
            --platform managed \
            --allow-unauthenticated \
            --migrate-traffic
