name: Cloud PostgreSQL Migrations

on:
  push:
    paths:
      - 'db/migrations/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'db/migrations/**'
    branches: [ "main" ]
jobs:
  run-migrations:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Run SQL migrations
      env:
        PGHOST: ${{ secrets.DB_HOST }}
        PGPORT: 5432
        PGDATABASE: ${{ secrets.DB_NAME }}
        PGUSER: ${{ secrets.DB_USER }}
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # Create SSL directory
        mkdir -p ~/.postgresql

        # Download the Cloud SQL public certificate
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.postgres.crt -O ~/.postgresql/root.crt

        for file in db/migrations/*.sql
        do
          echo "Running migration: $file"
          PGSSLMODE=verify-ca psql -f "$file"
        done
